#!/usr/bin/ruby

require "pathname" 
require "fileutils"
UP_PATH = Pathname.new(ENV["HOME"]).join("Library/Application\ Support/TuxPaint/starters/")
TP_PATH = Pathname.new(ENV["HOME"]).join("Library/Application\ Support/TuxPaint")
Dir.mkdir(TP_PATH) unless TP_PATH.exist?
Dir.mkdir(UP_PATH) unless UP_PATH.exist?
puts "Writing to #{UP_PATH}"
def upload(img_path)
	puts "Attempting to move #{img_path}"
	if img_path.directory?
		puts "Directory; moving inwards..."
		img_path.each_child do |c|
			upload(c)
		end
	elsif img_path.file? && /\.jpg|\.png|.svg/ =~ img_path.extname
		puts "It's a file; copying over..."
		FileUtils.copy(img_path, UP_PATH)
	else
		puts "Not a file or folder, dummy!"
	end
end
ARGV.each do |a|
	arg_path = Pathname.new(a)
	upload(arg_path)
end
FileUtils.chmod_R(0755, UP_PATH)
	
